model:
  name: resnet18
  embedding_dim: 128
  n_heads: 4
  n_layers: 2
  learning_rate: 1e-4
  weights: "DEFAULT"
  similarity_type: "bilinear"
  temperature: 0.1
  dropout_p: 0.1

training:
  max_epochs: 1
  batch_size: 16 # BÖR VARA SAMMA SOM I DATASET
  num_workers: 0
  overfit_batches: 0.0
  logger_dir: "/Users/erikwirdemark/deep-mash/logs"
  log_name: "baseline"

audio:
  target_sample_rate: 16000
  chunk_duration_sec: 15
  min_chunk_duration_sec: 5
  n_mels: 64
  f_min: 60
  f_max: 7800
  n_fft: 1024
  hop_size: 320
  vocal_energy_threshold: 0.01

data:
  input_root: "/Users/erikwirdemark/deep-mash/data/genres_stems"
  originals_root: "/Users/erikwirdemark/deep-mash/data/genres_original"
  processed_root: "/Users/erikwirdemark/deep-mash/data/processed"
  save_model: "/Users/erikwirdemark/deep-mash/data/saved_models/baseline" # ändra för olika körningar
  output:    "/Users/erikwirdemark/deep-mash/results/baseline"

dataset: 
  name: "gtzan_stems"
  seed: 42
  batch_size: 16
  split: "train"
  num_workers: 0
  val_split: 0.1
  test_split: 0.1

query:
  embeddings_prefix: "dataset"
  which_query: "vocal"
  which_catalogue: "instr"
  top_k: 5

